apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: clo835
  region: us-east-1
  version: "1.30"

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c

managedNodeGroups:
  - name: nodegroup
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 30
    ssh:
      allow: true
    enableSSM: true
    iam:
      instanceRoleARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/eks-node-role

iam:
  withOIDC: true
  serviceRoleARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/eks-service-role
  serviceAccounts:
    - metadata:
        name: clo835
        namespace: final
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly 