apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: clo835
  region: us-east-1
  version: "1.30"

availabilityZones:
  - us-east-1a
  - us-east-1b

managedNodeGroups:
  - name: nodegroup
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 30
    ssh:
      allow: true
    enableSSM: true
    iam:
      instanceRoleARN: arn:aws:iam::051034484218:role/eks-node-role
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        albIngress: true
        cloudWatch: true
        s3: true

iam:
  withOIDC: true
  serviceRoleARN: arn:aws:iam::051034484218:role/eks-service-role
  serviceAccounts:
    - metadata:
        name: clo835
        namespace: final
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly 