apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: final
type: Opaque
stringData:
  MYSQL_USER: root
  MYSQL_PASSWORD: my-secret-pw
  AWS_ACCESS_KEY_ID: your-access-key-id
  AWS_SECRET_ACCESS_KEY: your-secret-access-key

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: final
type: Opaque
data:
  username: cm9vdA==  # root
  password: ZGJfcGFzczEyMw==  # db_pass123
